### PR TITLE
15--general-styles colors

### PR DESCRIPTION
**Pull request by mariohernandez**
Updated color styles by implementing color swatches using brand colors.

colors

### CODE REVIEW

**Comment by thamas** [comment]
It is a much nicer display! 
Do not we need the contrast testing text which was in the color boxes?

**Comment by lauriii** [comment]
@thamas I'd assume we have various different possible text colors so I'm not sure if this is the best way to test the contrast.

**Review by lauriii — APPROVED** [review]

**Comment by kjays** [comment]
Looks good. Mark created the text over coloured blocks as a way of running a test against the styleguide for accessibility contrast checks. I think there is a service that he is planning on using. However, the variations in the design for text over background colours are reasonably limited and perhaps if we include such a feature, it would make sense to limit the illustrations to just those in the designs. I can help on this when the time comes.

**Comment by markconroy** [comment]
This looks great. Mine was a quick solution and if we don't have many text on backgrounds it'll be easy to manually run tests.

**Pull request merged**
